"""add discount to subscriptions

Revision ID: 015dc466f5cc
Revises: ef381eb5c8d1
Create Date: 2026-03-29 15:53:14.283642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015dc466f5cc'
down_revision: Union[str, Sequence[str], None] = 'ef381eb5c8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('discount_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'discount_amount')
    op.drop_column('subscriptions', 'discount_percent')
    # ### end Alembic commands ###
