"""add growth_rate to social metrics

Revision ID: 0d1f0fd389ce
Revises: c3548342a8cc
Create Date: 2026-03-26 12:54:52.029822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1f0fd389ce'
down_revision: Union[str, Sequence[str], None] = 'c3548342a8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_metrics', sa.Column('growth_rate', sa.Float(), nullable=True))
    op.alter_column('social_metrics', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('social_metrics', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('social_metrics', 'likes')
    op.drop_column('social_metrics', 'following')
    op.drop_column('social_metrics', 'comments')
    op.drop_column('social_metrics', 'shares')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_metrics', sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('social_metrics', sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('social_metrics', sa.Column('following', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('social_metrics', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('social_metrics', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('social_metrics', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('social_metrics', 'growth_rate')
    # ### end Alembic commands ###
