"""add plan_id to subscriptions

Revision ID: 350792a708da
Revises: 72d6f93b0bb0
Create Date: 2026-03-29 16:22:15.374726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '350792a708da'
down_revision: Union[str, Sequence[str], None] = '72d6f93b0bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'plan_id')
    # ### end Alembic commands ###
