"""add timestamps to subscriptions

Revision ID: 72d6f93b0bb0
Revises: 015dc466f5cc
Create Date: 2026-03-29 16:17:23.623361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d6f93b0bb0'
down_revision: Union[str, Sequence[str], None] = '015dc466f5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('subscriptions_plan_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'discount_amount')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_column('subscriptions', 'discount_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('discount_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('subscriptions_plan_id_fkey'), 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    # ### end Alembic commands ###
