"""add updated_at to subscriptions

Revision ID: 80a52bf90c7d
Revises: ea8aeb23f029
Create Date: 2026-03-29 16:58:46.911719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a52bf90c7d'
down_revision: Union[str, Sequence[str], None] = 'ea8aeb23f029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('subscriptions', 'max_clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('max_clients', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'updated_at')
    # ### end Alembic commands ###
