"""add canceled_at to subscriptions

Revision ID: 881ff1241b38
Revises: 80a52bf90c7d
Create Date: 2026-03-29 17:01:43.019648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '881ff1241b38'
down_revision: Union[str, Sequence[str], None] = '80a52bf90c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('canceled_at', sa.DateTime(), nullable=True))
    op.drop_column('subscriptions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'canceled_at')
    # ### end Alembic commands ###
