"""fix subscription remove plan string

Revision ID: ea8aeb23f029
Revises: 350792a708da
Create Date: 2026-03-29 16:39:06.613506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8aeb23f029'
down_revision: Union[str, Sequence[str], None] = '350792a708da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('subscriptions', 'plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'created_at')
    # ### end Alembic commands ###
